### ISSUE TITLE
Run ERROR with OSX v1.2.3

### ISSUE THREAD

**Issue by jinxinslim** [gnosis/MultiSigWallet#100]
Uncaught Exception:
Error: Cannot find module ‘ethereumjs-tx‘
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/xx/Desktop/gnosis/OSX-x64-1.2.3.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.anonymous (/Users/xx/Desktop/gnosis/OSX-x64-1.2.3.app/Contents/Resources/app.asar/main.js:11:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by rohanpatel2602** [comment]
Manually installing ethereumjs-tx in the dapp folder solved this for me

**Comment by thesved** [comment]
But this is the desktop electron application, not the dapp.

**Comment by denisgranha** [comment]
sorry guys, there were some corruption with the build, it's solved in https://github.com/gnosis/MultiSigWallet/releases/tag/v1.2.4
