### ISSUE TITLE
MultisigWallet.sol Deployment issue

### ISSUE THREAD

**Issue by ChanPoyu** [gnosis/MultiSigWallet#154]
I was trying to deploy the MultisigWallet.sol Contract on Remix and got this issue.

> VM error: revert.
> revert	The transaction has been reverted to the initial state.
> Note: The constructor should be payable if you send value.	Debug the transaction to get more information.

It seems the problem comes from here.

```
    function MultiSigWallet(address[] _owners, uint _required)
        public
        validRequirement(_owners.length, _required)
    {
        for (uint i=0; i<_owners.length; i++) {
            require(!isOwner[_owners[i]] && _owners[i] != 0);
            isOwner[_owners[i]] = true;
        }
        owners = _owners;
        required = _required;
    }

```
I added a `payable` modifier to try to fix this issue. Dosn't work at all. Do any one has a solution?

**Comment by nanmu42** [comment]
My deployement works fine.
Perhaps you should check your args in constructor?

**Comment by ChanPoyu** [comment]
@nanmu42 thanks for comment. I just copy and paste the whole source code.  what kind of Environment are you working on?

**Comment by ChanPoyu** [comment]
@nanmu42 
I tried truffle to deploy the contract. Here is the log
```
Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0xc755e124ca5d5535f60313140317f0a198a01184182f08b892f8bc8853be514e
  Migrations: 0x7319f7f69fafe57584fde7116b3491cb8ebb34f2
Saving successful migration to network...
  ... 0xb681ac01f4e7c956cee7a616ebf743cedf7d5e774cb4f70ace5bd7f27a46ba75
Saving artifacts...
Running migration: 2_deploy_contracts.js
Multisig with daily limit requires to pass owner list, required confirmations and daily limit
Saving successful migration to network...
  ... 0x774006eca43ceca1f140567093ad88925f185d3fce9ea7ab54a04f441fd8f52b
Saving artifacts...
truffle(development)> MyContract.at("0x8c513ccfd6de332a0fc705ae51d1ff49525bb6ce").getValue.call()
ReferenceError: MyContract is not defined
```
and I checked the deploy js code. It seems a error when` Multisig with daily limit requires to pass owner list, required confirmations and daily limit ` pops out.

Could anyone kindly show me the successfully deployed log?

**Comment by nanmu42** [comment]
Is `truffle test` working?

**Comment by nanmu42** [comment]
Did you feed the constructor needed args(owners, required, etc) in input data?
If `truffle test` works well, the contract is intact.

**Comment by ChanPoyu** [comment]
I tried again ` truffle test ` and failed.

These are the log I got.

```
Multisig with daily limit requires to pass owner list, required confirmations and daily limit


  Contract: MultiSigWallet
    1) "before each" hook for "test execution after requirements changed"

  Contract: MultiSigWallet
Multisig with daily limit requires to pass owner list, required confirmations and daily limit
    2) "before each" hook for "transferWithPayloadSizeCheck"

  Contract: MultiSigWalletWithDailyLimit
Multisig with daily limit requires to pass owner list, required confirmations and daily limit
    3) "before each" hook for "create multisig"

  Contract: MultiSigWalletWithDailyLimitFactory
Multisig with daily limit requires to pass owner list, required confirmations and daily limit
    4) Multisig Factory
    > No events were emitted


  0 passing (7m)
  4 failing

  1) Contract: MultiSigWallet
       "before each" hook for "test execution after requirements changed":
     Error: The contract code couldn't be stored, please check your gas amount.
      at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Contract: MultiSigWallet
       "before each" hook for "transferWithPayloadSizeCheck":
     Error: The contract code couldn't be stored, please check your gas amount.
      at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  3) Contract: MultiSigWalletWithDailyLimit
       "before each" hook for "create multisig":
     Error: The contract code couldn't be stored, please check your gas amount.
      at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  4) Contract: MultiSigWalletWithDailyLimitFactory
       Multisig Factory:
     Error: Transaction: 0xc5472c2e74253f332f8eb6d849d67251b41a48aba57c5f2c0db1121f09e0d750 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.

      at StatusError.ExtendableError (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-error/index.js:10:1)
      at new StatusError (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/statuserror.js:29:1)
      at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:181:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

```
Do I need to increase my gas limit?
It look like the ` MultiSigWallet.sol ` cost really a lot.
Is there any URL related to the gas limit solution?

**Comment by nanmu42** [comment]
Try Ganache as rpc end point.

truffleframework.com/ganache/

**Comment by nanmu42** [comment]
My last deployment succeeded at 14 days ago, on master branch.

**Comment by ChanPoyu** [comment]
@nanmu42 `truffle test` works fast and nice on Ganache. Thanks a lot.

**Comment by nanmu42** [comment]
You are welcome.
