### ISSUE TITLE
Why is node 8 a requirement for Mac 10.14.6?

### ISSUE THREAD

**Issue by ktsuttlemyre** [gnosis/MultiSigWallet#313]
Environment:
mac - 10.14.6 
node -12.12.0

Error:
```
 npm install node-hid

> node-hid@0.5.7 install /Users/kyles/Projects/node-steam-controller/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.4.0 runtime=node arch=x64 platform=darwin)
  CC(target) Release/obj.target/hidapi/hidapi/mac/hid.o
../hidapi/mac/hid.c:252:20: warning: comparison of integers of different signs:
      'CFIndex' (aka 'long') and 'size_t' (aka 'unsigned long') [-Wsign-compare]
                if (chars_copied == len)
                    ~~~~~~~~~~~~ ^  ~~~
1 warning generated.
  LIBTOOL-STATIC Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:203:43: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      Nan::GetCurrentContext()->Global()->Get(Nan::New<String>("Buffer")...
                                          ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3412:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:207:45: error: no matching member function for call to
      'NewInstance'
    Local<Object> buf = nodeBufConstructor->NewInstance(1, nodeBufferArgs);
                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:4134:44: note: candidate
      function not viable: requires single argument 'context', but 2 arguments
      were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:4131:44: note: candidate
      function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/HID.cc:231:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  iocb->_callback->Call(2, argv);
                   ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/HID.cc:280:13: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    retval->Set(i, Nan::New<Integer>(buff_read[i]));
            ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3367:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:305:13: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    retval->Set(i, Nan::New<Integer>(buff_read[i]));
            ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3367:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:339:13: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    retval->Set(i, Nan::New<Integer>(buf[i]));
            ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3367:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:360:24: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    if (!messageArray->Get(i)->IsNumber()) {
                       ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:363:53: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    message.push_back((unsigned char) messageArray->Get(i)->Int32Value());
                                                    ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:363:72: error: too few arguments to function call, single argument
      'context' was not specified
    message.push_back((unsigned char) messageArray->Get(i)->Int32Value());
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:404:46: error: too few arguments to function call, single argument
      'context' was not specified
      int32_t vendorId = info[0]->Int32Value();
                         ~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:405:47: error: too few arguments to function call, single argument
      'context' was not specified
      int32_t productId = info[1]->Int32Value();
                          ~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:409:37: error: no matching conversion for functional-style cast
      from 'v8::Local<v8::Value>' to 'v8::String::Value'
        serialPointer = (wchar_t*) *v8::String::Value(info[2]);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3025:5: note: candidate
      constructor not viable: no known conversion from 'v8::Local<v8::Value>' to
      'const v8::String::Value' for 1st argument
    Value(const Value&) = delete;
    ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3018:5: note: candidate
      constructor not viable: requires 2 arguments, but 1 was provided
    Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../src/HID.cc:443:37: error: too few arguments to function call, single argument
      'context' was not specified
  blockStatus = info[0]->Int32Value();
                ~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:468:26: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      if (!messageArray->Get(i)->IsNumber()) {
                         ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:471:55: warning: 'Get' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      message.push_back((unsigned char) messageArray->Get(i)->Int32Value());
                                                      ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3416:3: note: 'Get' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:471:74: error: too few arguments to function call, single argument
      'context' was not specified
      message.push_back((unsigned char) messageArray->Get(i)->Int32Value());
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:504:17: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    deviceInfo->Set(Nan::New<String>("manufacturer").ToLocalChecked(),
                ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:508:17: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    deviceInfo->Set(Nan::New<String>("product").ToLocalChecked(),
                ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:512:17: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    deviceInfo->Set(Nan::New<String>("serialNumber").ToLocalChecked(),
                ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:535:38: error: too few arguments to function call, single argument
      'context' was not specified
      vendorId = info[0]->Int32Value();
                 ~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:536:39: error: too few arguments to function call, single argument
      'context' was not specified
      productId = info[1]->Int32Value();
                  ~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:2569:3: note: 'Int32Value'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:551:17: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    deviceInfo->Set(Nan::New<String>("vendorId").ToLocalChecked(), Nan::...
                ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:552:17: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    deviceInfo->Set(Nan::New<String>("productId").ToLocalChecked(), Nan:...
                ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:554:19: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      deviceInfo->Set(Nan::New<String>("path").ToLocalChecked(), Nan::Ne...
                  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:557:19: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      deviceInfo->Set(Nan::New<String>("serialNumber").ToLocalChecked()...
                  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:560:19: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      deviceInfo->Set(Nan::New<String>("manufacturer").ToLocalChecked()...
                  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:563:19: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
      deviceInfo->Set(Nan::New<String>("product").ToLocalChecked(), Nan:...
                  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:565:17: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    deviceInfo->Set(Nan::New<String>("release").ToLocalChecked(), Nan::N...
                ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:566:17: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    deviceInfo->Set(Nan::New<String>("interface").ToLocalChecked(), Nan:...
                ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:568:21: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        deviceInfo->Set(Nan::New<String>("usagePage").ToLocalChecked(), ...
                    ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:571:21: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        deviceInfo->Set(Nan::New<String>("usage").ToLocalChecked(), Nan:...
                    ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3358:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:573:13: warning: 'Set' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    retval->Set(count++, deviceInfo);
            ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:3367:3: note: 'Set' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:322:29: note: expanded
      from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/HID.cc:614:82: error: too few arguments to function call, single argument
      'context' was not specified
  ...hidTemplate->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:5947:3: note: 'GetFunction'
      declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/HID.cc:616:115: error: too few arguments to function call, single
      argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(HID::devices)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8.h:5947:3: note: 'GetFunction'
      declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/kyles/.node-gyp/12.4.0/include/node/v8config.h:347:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
23 warnings and 11 errors generated.
make: *** [Release/obj.target/HID/src/HID.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kyles/Projects/node-steam-controller/node_modules/node-hid
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.5.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kyles/.npm/_logs/2019-10-18T00_25_13_942Z-debug.log
```
also tried running 
```npm install node-hid --build-from-source``` 
and got the same error

Came across this answer and it said to use node version 8.
https://github.com/gnosis/MultiSigWallet/issues/197

This fixes the problem and I am able to get the test suite to run but now I am forced to use node version 8.

**Comment by denisgranha** [comment]
hi @ktsuttlemyre it's basically due to two dependencies:
*  Ledger
* Electron

both updates break some code and also introduces a new firmware of Ledger that forces users to update their ledger versions to continue using it. We have not planned implementing this break changes, but if someone does implement it, I would review it with care

Thanks
