### ISSUE TITLE
Tests crash

### ISSUE THREAD

**Issue by wschwab** [gnosis/MultiSigWallet#72]
Hi! I love the wallet so far, and forked it after seeing it highly praised by the community. I've run into a problem, though: Running the test script with `npm test` on Windows 10 (git bash) gives the following error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn testrpc ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn testrpc ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn testrpc ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
npm ERR! Test failed.  See above for more details.
```

**Comment by denisgranha** [comment]
Hi @wschwab what version of NPM and Node are you using?

**Comment by wschwab** [comment]
npm: 3.10.10
node: 6.10.2
